git-credential-lastpass: login if required

diff --git a/git-credential-lastpass b/git-credential-lastpass
--- a/git-credential-lastpass
+++ b/git-credential-lastpass
@@ -63,40 +63,40 @@ while read -r line && [ -n "$line" ]; do
     esac
 done
 
-# if [ ! $(lpass status -q) ]; then
-#     if [ "$LPASS_DISABLE_PINENTRY" != "1" ]; then
-#         if [ -n "$LPASS_PINENTRY" ]; then
-#             pinentry=$LPASS_PINENTRY
-#         else
-#             pinentry="pinentry"
-#         fi
-#         if [ -x "$(unset -f command; command -v $pinentry)" ]; then
-# 			lpassuser=$(
-# 				$pinentry << EOF | grep '^D ' | cut -d ' ' -f 2
-# SETTITLE git-credential-lastpass
-# SETDESC Please enter the e-mail address for LastPass account.
-# SETPROMPT e-mail address:
-# GETPIN
-# EOF
-#             )
-#         fi
-#     fi
-#     if [ -z "$lpassuser" ] && [ -n "$LPASS_ASKPASS" ] && [ -x "$(\\unset -f command; \\command -v $LPASS_ASKPASS)" ]; then
-#         lpassuser=$(
-#             $LPASS_ASKPASS "e-mail address:"
-#         )
-#     fi
-#     if [ -z "$lpassuser" ]; then
-# 		read -r -p "Lastpass: login required. Lastpass username: " lpassuser </dev/tty >/dev/tty
-#     fi
-# 	if [ -z "$lpassuser" ]; then
-# 		exit
-# 	fi
-# 	if ! lpass login "$lpassuser" >&2; then
-# 		echo "Lastpass: failed to login" >&2
-# 		exit
-# 	fi
-# fi
+if [ ! $(lpass status -q) ]; then
+    if [ "$LPASS_DISABLE_PINENTRY" != "1" ]; then
+        if [ -n "$LPASS_PINENTRY" ]; then
+            pinentry=$LPASS_PINENTRY
+        else
+            pinentry="pinentry"
+        fi
+        if [ -x "$(unset -f command; command -v $pinentry)" ]; then
+			lpassuser=$(
+				$pinentry << EOF | grep '^D ' | cut -d ' ' -f 2
+SETTITLE git-credential-lastpass
+SETDESC Please enter the e-mail address for LastPass account.
+SETPROMPT e-mail address:
+GETPIN
+EOF
+            )
+        fi
+    fi
+    if [ -z "$lpassuser" ] && [ -n "$LPASS_ASKPASS" ] && [ -x "$(\\unset -f command; \\command -v $LPASS_ASKPASS)" ]; then
+        lpassuser=$(
+            $LPASS_ASKPASS "e-mail address:"
+        )
+    fi
+    if [ -z "$lpassuser" ]; then
+		read -r -p "Lastpass: login required. Lastpass username: " lpassuser </dev/tty >/dev/tty
+    fi
+	if [ -z "$lpassuser" ]; then
+		exit
+	fi
+	if ! lpass login "$lpassuser" >&2; then
+		echo "Lastpass: failed to login" >&2
+		exit
+	fi
+fi
 
 ids=$(
     lpass ls --format "%ai %al %au" | (
